server:
  port: 10086
  servlet:
    context-path: /server01
spring:
  application:
    name: server01
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test02?characterEncoding=utf-8
      username: root
      password: 741789
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
#  data:
#    mongodb:
#      uri: mongodb://root:741789@localhost:27017
#      database: xc_cms
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://eureka-10002.com:10002/eureka,eureka-10001.com:10001/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.43.187
