server:
  port: 10087
  servlet:
    context-path: /server02
spring:
  application:
    name: server02
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test02?characterEncoding=utf-8
      username: root
      password: 741789
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
#  data:
#    mongodb:
#      uri: mongodb://root:741789@localhost:27017
#      database: xc_cms
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://eureka-10002.com:10002/eureka,http://eureka-10001.com:10001/eureka


#server01:
#  ribbon:
#    ReadTimeout: 1000
#    ConnectTimeout: 1000
##    MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
##    MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#    OkToRetryOnAllOperations: false  #是否所有操作都重试
ribbon:
  ReadTimeout: 500
  ConnectTimeout: 2000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

feign:
  hystrix:
     enabled: true # 开启Feign的熔断功能，默认是false

hystrix:
  command:
#    SERVER01:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000  #熔断超时时间
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000  #熔断超时时间




