server:
  port: 10002 # 端口
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
eureka:
  instance:
    hostname: eureka-10002.com
#    instance-id: eureka-10002
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
    service-url:
#      defaultZone: http://127.0.0.1:10002/eureka
      defaultZone: http://eureka-10001.com:10001/eureka/

